CREATE TABLE Game (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    PlayedTime DATETIME NOT NULL,
    P1 INTEGER NOT NULL,
    P2 INTEGER NOT NULL,
    P3 INTEGER NOT NULL,
    P4 INTEGER NOT NULL,
    D1 INTEGER NOT NULL,
    D2 INTEGER NOT NULL,
    D3 INTEGER NOT NULL,
    D4 INTEGER NOT NULL,
    Winner INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (P1) REFERENCES Player (ID),
    FOREIGN KEY (P2) REFERENCES Player (ID),
    FOREIGN KEY (P3) REFERENCES Player (ID),
    FOREIGN KEY (P4) REFERENCES Player (ID),
    FOREIGN KEY (D1) REFERENCES Deck (ID),
    FOREIGN KEY (D2) REFERENCES Deck (ID),
    FOREIGN KEY (D3) REFERENCES Deck (ID),
    FOREIGN KEY (D4) REFERENCES Deck (ID)
);

CREATE TABLE Player (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE Deck (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CMDR VARCHAR(100) NOT NULL,
    DECKLINK VARCHAR(100) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE Plays (
    GID INTEGER NOT NULL,
    PID INTEGER NOT NULL,
    WINNER VARCHAR(1) NOT NULL,
    PRIMARY KEY(PID, GID),
    FOREIGN KEY (PID) REFERENCES Player (ID),
    FOREIGN KEY (GID) REFERENCES Game (ID)
);

CREATE TABLE Has (
    GID INTEGER NOT NULL,
    DID INTEGER NOT NULL,
    PRIMARY KEY(GID, DID),
    FOREIGN KEY (DID) REFERENCES Deck (ID),
    FOREIGN KEY (GID) REFERENCES Game (ID)
);

CREATE TABLE Owns (
    PID INTEGER NOT NULL,
    DID INTEGER NOT NULL,
    FOREIGN KEY (PID) REFERENCES Player (ID),
    FOREIGN KEY (DID) REFERENCES Deck (ID)
);
